name: upgrade-gh-cli tests

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: ["main"]
    paths: ["action.yml", ".github/workflows/upgrade-gh-cli-tests.yml"]

jobs:
  upgrade-gh-cli-and-assert:
    name: Upgrade gh cli and assert-upgraded
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Checkout composite actions repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: test-action
          ref: ${{ github.ref }}
      - name: Upgrade gh cli and assert-upgraded
        uses: ./test-action
        with:
          assert-upgraded: true

  upgrade-gh-cli-and-skip-assert:
    name: Upgrade gh cli and skip assertion
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Checkout composite actions repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: test-action
          ref: ${{ github.ref }}
      - name: Upgrade gh cli skip assert-upgraded
        uses: ./test-action
        with:
          assert-upgraded: false
